In [30]:
import numpy as np
import random

In [31]:
#A continuación, definimos las funciones de activación que utilizaremos en nuestra red neuronal
# utilizaremos la función sigmoide como función de activación para las capas ocultas y la función lineal como función de activación para la capa de salida

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def linear(x):
    return x

In [32]:
class NeuralNetwork:
    
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        # Inicializar los pesos aleatorios
        self.weights1 = np.random.rand(self.input_size, self.hidden_size)
        self.weights2 = np.random.rand(self.hidden_size, self.output_size)
        
    def forward(self, X):
        # Propagación hacia adelante
        self.hidden_layer = sigmoid(np.dot(X, self.weights1))
        self.output_layer = linear(np.dot(self.hidden_layer, self.weights2))
        
        return self.output_layer
    
    def backward(self, X, y, output):
        # Propagación hacia atrás
        self.output_error = y - output
        self.output_delta = self.output_error
        
        self.hidden_error = self.output_delta.dot(self.weights2.T)
        self.hidden_delta = self.hidden_error * sigmoid(self.hidden_layer) * (1 - sigmoid(self.hidden_layer))
        
        # Actualizar los pesos
        self.weights1 += X.T.dot(self.hidden_delta)
        self.weights2 += self.hidden_layer.T.dot(self.output_delta)
        
    def train(self, X, y, epochs):
        for i in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)

In [41]:
#creamos una instancia de la red neuronal con una capa de entrada de tamaño 2, una capa oculta de tamaño 3 y una capa de salida de tamaño 1. Luego, generamos algunos datos de entrenamiento y entrenamos la red neuronal durante 1000 épocas.

# Crear una instancia de la red neuronal
nn = NeuralNetwork(2, 3, 1)

# Generar datos de entrenamiento
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Entrenar la red neuronal
nn.train(X, y, epochs=1000)

# Imprimir los resultados
print("Input:\n" + str(X))
print("Predicted Output:\n" + str(nn.forward(X)))
print("Actual Output:\n" + str(y))


Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Predicted Output:
[[-0.02388473]
 [ 0.54251219]
 [ 0.54148936]
 [ 0.04131165]]
Actual Output:
[[0]
 [1]
 [1]
 [0]]


In [38]:
#la red neuronal debe ser capaz de aprender la función XOR, donde la salida es 1 si solo uno de los valores de entrada es 1 y 0 en cualquier otro caso.